packages:
  - name: openai
    actions:
      - name: completion
        runtime: 'nodejs:default'
        web: true
        environment:
          apiKey: "${apiKey}"
        limits:
          timeout: 30000
